//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class TestSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestSettings defaultInstance = ((TestSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestSettings())));
        
        public static TestSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9611cb3f-fc80-4892-82cd-8179f4f47dd2")]
        public string AzureSubscriptionId {
            get {
                return ((string)(this["AzureSubscriptionId"]));
            }
            set {
                this["AzureSubscriptionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6610C4733825B78DB1AB5D1EEE1B924B457EF0A0")]
        public string ManagementCertificateThumbprint {
            get {
                return ((string)(this["ManagementCertificateThumbprint"]));
            }
            set {
                this["ManagementCertificateThumbprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public int DefaultProgramArchivalWindowMinutes {
            get {
                return ((int)(this["DefaultProgramArchivalWindowMinutes"]));
            }
            set {
                this["DefaultProgramArchivalWindowMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int OverlappingArchivalWindowMinutes {
            get {
                return ((int)(this["OverlappingArchivalWindowMinutes"]));
            }
            set {
                this["OverlappingArchivalWindowMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testsabbour")]
        public string MediaServiceAccountName {
            get {
                return ((string)(this["MediaServiceAccountName"]));
            }
            set {
                this["MediaServiceAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15EX/zqcBy2S08j/Z0dMUn0IblZOS84tJWh3GqVINJw=")]
        public string MediaServiceAccountKey {
            get {
                return ((string)(this["MediaServiceAccountKey"]));
            }
            set {
                this["MediaServiceAccountKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mediaschedulertest.onmicrosoft.com")]
        public string AADTenant {
            get {
                return ((string)(this["AADTenant"]));
            }
            set {
                this["AADTenant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c7af6876-e451-42ee-9939-a62371882f66")]
        public string AADClientId {
            get {
                return ((string)(this["AADClientId"]));
            }
            set {
                this["AADClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jfW9At167tEvb5K4BFBJl/Nb2FuybUbQai4mu0Vg51E=")]
        public string AADSecret {
            get {
                return ((string)(this["AADSecret"]));
            }
            set {
                this["AADSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ArchivalWindowMinutes {
            get {
                return ((int)(this["ArchivalWindowMinutes"]));
            }
            set {
                this["ArchivalWindowMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("North Europe")]
        public string SchedulerRegion {
            get {
                return ((string)(this["SchedulerRegion"]));
            }
            set {
                this["SchedulerRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://postcatcher.in/catchers/54c7a0044d0a5c030000076a")]
        public string ScheduleManagerEndpoint {
            get {
                return ((string)(this["ScheduleManagerEndpoint"]));
            }
            set {
                this["ScheduleManagerEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://management.core.windows.net/")]
        public string AADAudience {
            get {
                return ((string)(this["AADAudience"]));
            }
            set {
                this["AADAudience"] = value;
            }
        }
    }
}
